export const NAME_MEANINGS: Record<string, string> = {
  // Yoruba
  adeyemi: "Yoruba for 'the crown befits me'.",
  babatunde: "Yoruba for 'the father has returned'.",
  olujinmi: "Yoruba name meaning 'the divine wakes me with a gift'.",
  kayode: "Yoruba for 'he brings joy'.",
  amara: "Derived from many African languages meaning 'grace' or 'eternal'.",
  yetunde: "Yoruba for 'the mother has returned'.",
  folake: "Yoruba meaning 'cherished with wealth and care'.",
  temitope: "Yoruba for 'mine is worthy of thanks'.",
  ola: "Yoruba short form for riches or honor, literally 'wealth'.",
  taiwo: "Yoruba for 'the first twin to taste the world'.",
  ayodele: "Yoruba meaning 'joy has come home'.",
  oba: "Title meaning 'king' in Yoruba.",
  ori: "Yoruba concept of inner head or destiny.",
  yemo: "Short for Yemọja, the mother of waters in Yoruba cosmology.",

  // Igbo
  chinedu: "Igbo for 'God leads'.",
  obinna: "Igbo meaning 'father's heart'.",
  emeka: "Short for Chukwuemeka, 'God has done great'.",
  ugochukwu: "Igbo for 'God's glory'.",
  adaeze: "Igbo meaning 'princess'.",
  ngozi: "Igbo for 'blessing'.",
  chimaka: "Igbo phrase for 'God is beautiful'.",
  oluchi: "Igbo meaning 'God's work'.",
  kelechi: "Igbo for 'thank God'.",
  ife: "Igbo and Yoruba word for 'love'.",
  damili: "Derived from Damilola, meaning 'bless me with wealth'.",
  nma: "Igbo word for 'beauty'.",
  udo: "Igbo for 'peace'.",

  // Arabic
  idris: "Arabic name meaning 'studious' or 'interpreter'.",
  jibril: "Arabic form of Gabriel, 'God is my strength'.",
  zayd: "Arabic name meaning 'growth, abundance'.",
  karim: "Arabic for 'generous, noble'.",
  layla: "Arabic for 'night'.",
  mariam: "Semitic name meaning 'beloved' or 'rebellious'.",
  soraya: "Persian-Arabic for 'Pleiades' (cluster of stars).",
  zahra: "Arabic for 'radiant, flowering'.",
  noor: "Arabic word for 'light'.",
  amani: "Arabic for 'wishes, aspirations'.",
  raf: "Short for Rafi, meaning 'elevated, noble'.",
  azar: "Persian-Arabic for 'fire'.",
  nur: "Variant of Noor meaning 'light'.",
  haqq: "Arabic for 'truth, righteousness'.",

  // European
  lucian: "From Latin 'lux', meaning 'light'.",
  matthias: "Greek form of Matthew, 'gift of God'.",
  sebastian: "From Sebastos, meaning 'venerable'.",
  rene: "French form of Renatus, 'reborn'.",
  elara: "Greek mythic name tied to moonlit wanderers.",
  vivienne: "French for 'alive, lively'.",
  isolde: "Old Germanic name meaning 'ice battle'.",
  rowena: "Old English name meaning 'fame and joy'.",
  jules: "From Julian, meaning 'youthful'.",
  adrian: "From Hadrianus, 'dark one' or 'from the Adriatic'.",
  sasha: "Slavic diminutive of Alexander, 'defender of men'.",
  rune: "Old Norse word for 'secret lore'.",
  vale: "Old English for 'valley' or 'dweller of the valley'.",

  // Celtic
  finnian: "From Fionnán, meaning 'little fair one'.",
  cormac: "Gaelic name meaning 'raven' or 'son of the charioteer'.",
  ronan: "Irish name meaning 'little seal'.",
  aeron: "Welsh name meaning 'berry' or linked to the deity Aeron.",
  eira: "Welsh for 'snow'.",
  niamh: "Irish mythic name meaning 'bright'.",
  siobhan: "Irish form of Joan, 'God is gracious'.",
  rhiannon: "Welsh goddess name meaning 'great queen'.",
  quinn: "From Conn, meaning 'chief' or 'wisdom'.",
  morgan: "Welsh for 'sea-born' or 'bright sea'.",
  dilys: "Welsh word meaning 'genuine, true'.",
  bryn: "Welsh for 'hill'.",
  thorne: "Old English word for a thorn tree, symbolizing protection.",

  // Norse
  bjorn: "Old Norse for 'bear'.",
  leif: "Old Norse meaning 'descendant, heir'.",
  soren: "From Severinus, interpreted as 'stern'.",
  eirik: "Old Norse for 'ever-ruler'.",
  astrid: "Old Norse for 'divine strength'.",
  freya: "Norse goddess of love and battle.",
  signe: "Old Norse meaning 'new victory'.",
  liv: "Old Norse word for 'life'.",
  skadi: "Giantess of winter in Norse myth.",
  storm: "English/Norse word for tempestuous weather.",
  nika: "Slavic short form of Veronica, 'victory'.",
  frost: "English word evoking icy breath.",
  drake: "From Old English 'draca', meaning dragon.",

  // Angelic order
  azrael: "Hebrew 'Azra'el' meaning 'help of God'.",
  cassiel: "From qafsiel, interpreted as 'speed of God'.",
  uriel: "Hebrew for 'God is my light'.",
  raphael: "Hebrew for 'God heals'.",
  gabriel: "Hebrew for 'God is my strength'.",
  michael: "Hebrew for 'Who is like God?'.",
  raziel: "Hebrew for 'Secrets of God'.",
  sariel: "Hebrew for 'Prince of God'.",
  seraphina: "From 'seraph', meaning 'fiery one'.",
  celestia: "Latin for 'heavenly'.",
  auriel: "Variant of Uriel meaning 'golden light of God'.",
  evangeline: "Greek for 'bearer of good news'.",
  angelica: "Latin adjective meaning 'angelic'.",
  mercy: "Virtue name meaning compassion.",
  grace: "Virtue name for divine favor.",
  ariel: "Hebrew for 'lion of God'.",
  jophiel: "Hebrew for 'beauty of God'.",
  haniel: "Hebrew for 'grace of God'.",
  zadkiel: "Hebrew for 'righteousness of God'.",
  metatron: "Mystical title for the celestial scribe of the throne.",
  lux: "Latin for 'light'.",
  seraph: "From Hebrew 'saraph', 'burning one'.",
  herald: "Old French heraut, 'messenger'.",
  sanctus: "Latin for 'holy'.",
  radiant: "English descriptor for shining light.",

  // Demon order
  belial: "Hebrew for 'worthless' later reinterpreted as a fallen one.",
  amon: "Name linked to the Egyptian god Amun, 'the hidden one'.",
  asmodeus: "From Aeshma-deva, 'demon of wrath'.",
  bael: "Variant of Baal, 'lord'.",
  malphas: "Goetic spirit known as the builder of towers.",
  vassago: "Goetic prince of prophecy.",
  ronove: "Goetic marquis of rhetoric and knowledge.",
  cain: "Biblical name meaning 'acquired'.",
  lilith: "From Sumerian lilitu, 'night creature'.",
  naamah: "Hebrew for 'pleasant'.",
  agrat: "Agrat bat Mahlat, queen of seductions.",
  mahalath: "Name meaning 'stringed instrument' or 'dancer'.",
  proserpina: "Latin form of Persephone, spring queen of the underworld.",
  eisheth: "Eisheth Zenunim, demoness of fornication.",
  jezebel: "Phoenician name meaning 'unexalted'.",
  baphomet: "Mystic idol symbolizing union of opposites.",
  leviathan: "Hebrew sea serpent meaning 'twisted one'.",
  abaddon: "Hebrew for 'destruction'.",
  samael: "Hebrew 'venom of God'.",
  azazel: "Hebrew scapegoat spirit meaning 'strong one of God'.",
  beleth: "Goetic king commanding infernal legions.",
  shade: "English term for a shadow spirit.",
  nox: "Latin for 'night'.",
  void: "English for the emptiness between worlds.",
  umbra: "Latin for 'shadow'.",
  ater: "Latin word for 'black, dark'.",

  // Jinn order
  iblis: "Arabic name of the rebellious jinn, possibly 'despair'.",
  malik: "Arabic for 'king'.",
  ghul: "Arabic ghûl meaning 'desert shapeshifter'.",
  marid: "Arabic for 'rebellious, gigantic spirit'.",
  ifrit: "Arabic for a class of smokeless fire jinn.",
  qarin: "Arabic for a companion spirit.",
  "zawba'ah": "Arabic whirlwind demon of storms.",
  zara: "Arabic for 'radiance'.",
  shams: "Arabic for 'sun'.",
  laila: "Alternative spelling of Layla meaning 'night'.",
  qamar: "Arabic for 'moon'.",
  nasim: "Arabic for 'breeze'.",
  samira: "Arabic for 'evening storyteller'.",
  ruhina: "From ruh, meaning 'spirit'.",
  shaitan: "Arabic for 'adversary'.",
  buraq: "Mythic steed meaning 'lightning'.",
  zephyr: "Greek Zephyros, 'west wind'.",
  simoom: "Arabic for 'poison wind'.",
  haboob: "Sudanese Arabic term for a massive dust storm.",
  djinn: "Arabic jinn, 'hidden spirit'.",
  smokeless: "Refers to Quranic 'smokeless fire' origin.",
  flame: "English for fire.",
  mirage: "Optical illusion above hot sands.",
  sirocco: "Mediterranean desert wind.",

  // Human heroes
  arthur: "Celtic legendary king, possibly 'bear-man'.",
  odysseus: "Greek hero whose name hints at 'wrathful'.",
  beowulf: "Old English 'bee-wolf', a kenning for bear.",
  gilgamesh: "Sumerian hero-king of Uruk.",
  achilles: "Possibly 'grief of the people'.",
  siegfried: "Old Germanic 'victory peace'.",
  roland: "Frankish hero meaning 'famous land'.",
  morgana: "Fey sorceress name meaning 'sea circle'.",
  penelope: "Greek for 'duck' or 'weaver'.",
  judith: "Hebrew Yehudit, 'praised'.",
  boudica: "Brythonic for 'victory'.",
  mulan: "Chinese name meaning 'magnolia blossom'.",
  joan: "From Johanna, 'God is gracious'.",
  cleopatra: "Greek for 'glory of the father'.",
  robin: "From Robert, 'bright fame'.",
  merlin: "From Myrddin, 'sea hill'.",
  sage: "Latin for 'wise'.",
  percival: "Old French 'pierce the valley'.",
  lancelot: "Possibly 'land servant' or diminutive of Lance.",
  champion: "English word meaning victor of contests.",
  wanderer: "English for the one who roams.",
  hero: "Greek hērōs meaning 'protector'.",
  seeker: "English for one who quests.",
  survivor: "English word for one who endures.",

  // Titan order
  atlas: "Titan who bears the heavens.",
  prometheus: "Greek for 'forethought'.",
  hyperion: "Greek for 'the watcher from above'.",
  kronos: "Titan of time and cycles.",
  oceanus: "Titan of the encircling sea.",
  helios: "Greek sun god whose name means 'sun'.",
  coeus: "Titan of inquiry and intellect.",
  rhea: "Titaness mother of the Olympians.",
  themis: "Greek personification of divine law.",
  phoebe: "Greek for 'bright'.",
  tethys: "Titaness of the nourishing waters.",
  mnemosyne: "Titaness of memory.",
  theia: "Titaness of shining light.",
  dione: "Ancient mother goddess associated with oracles.",
  metis: "Titaness of cunning wisdom.",
  leto: "Titaness mother of Artemis and Apollo.",
  asteria: "Ancient Greek for 'of the stars'.",
  selene: "Greek moon goddess.",
  eos: "Greek dawn goddess.",
  colossus: "Greek word for giant statue, symbolizing immensity.",
  elder: "Title denoting primordial age.",
  primeval: "Refers to the first ages of the cosmos.",
  vast: "Describes immeasurable expanse.",
  ancient: "Denotes immeasurable antiquity.",

  // Fae order
  oberon: "Legendary fairy king whose name means 'noble bear'.",
  puck: "Mischievous sprite from English folklore.",
  finvarra: "Irish fairy king of the west.",
  ailill: "Old Irish meaning 'beauty'.",
  gwyn: "Welsh for 'white, blessed'.",
  pwyll: "Welsh prince known for cunning exchanges.",
  midir: "Irish lord of the underworld mound.",
  titania: "Shakespearean fairy queen meaning 'great one'.",
  mab: "Faerie queen from British lore.",
  oonagh: "Irish fairy queen also spelled Una.",
  aine: "Irish goddess of summer and sovereignty.",
  maeve: "Anglicized Medb, 'intoxicating'.",
  etain: "Mythic heroine meaning 'jealousy' or 'passion'.",
  gossamer: "Word for delicate fairy cloth.",
  willow: "Tree associated with enchantment.",
  thorn: "Defensive yet sacred plant symbol.",
  bramble: "Briar thicket guarding fae realms.",
  elderwood: "Ancient fae timber symbolizing portals.",
  moonshade: "Poetic phrase for moonlit shadow.",
  sprite: "Term for tiny fae spirit.",
  pixie: "Cornish fae being.",
  changeling: "Folk tale child swapped by fae.",
  wisp: "Ghostly light leading travelers astray.",
  glimmer: "Soft shimmering light of glamour.",

  // Yokai order
  tengu: "Japanese mountain spirit meaning 'heavenly dog'.",
  kappa: "Water imp meaning 'river child'.",
  oni: "Japanese ogre or demon.",
  raijin: "Shinto thunder god.",
  fujin: "Shinto wind god.",
  inugami: "'Dog spirit' familiar in Japanese sorcery.",
  ryujin: "Dragon god of the sea.",
  kitsune: "Japanese fox spirit.",
  "yuki-onna": "'Snow woman' yokai of winter storms.",
  jorogumo: "'Binding bride', spider woman yokai.",
  "futakuchi-onna": "'Two-mouthed woman' yokai.",
  "nure-onna": "'Wet woman' serpent yokai.",
  "hone-onna": "'Bone woman' revenant spirit.",
  tanuki: "Raccoon-dog trickster.",
  kodama: "Tree spirit.",
  nue: "Chimeric beast of ill omens.",
  kirin: "Benevolent qilin/kirin creature.",
  tsukumogami: "Animate artifact spirit.",
  bakeneko: "Shapeshifting cat spirit.",
  obake: "General shapeshifting ghost.",
  mujina: "Badger spirit known for illusions.",
  henge: "Japanese for metamorphosis.",
  yasha: "From Yaksha, fierce guardian spirit.",
  kamikaze: "'Divine wind' that saved Japan.",

  // Elemental order
  ignis: "Latin for fire.",
  aquilo: "Roman north wind.",
  zephyrus: "Greek west wind.",
  geo: "From Greek for earth.",
  vulcan: "Roman god of forge and flame.",
  boreas: "Greek north wind.",
  notus: "Greek south wind.",
  undine: "Water elemental spirit.",
  sylph: "Air elemental spirit.",
  salamandra: "Alchemical fire elemental.",
  terra: "Latin for earth.",
  aura: "Latin for breeze.",
  marina: "From mare, meaning 'of the sea'.",
  gnome: "Earth elemental spirit.",
  nymph: "Nature spirit.",
  dryad: "Tree nymph.",
  naiad: "Freshwater nymph.",
  oread: "Mountain nymph.",
  blaze: "Flame.",
  torrent: "Rushing water.",
  gale: "Strong wind.",
  quake: "Earth tremor.",
  tempest: "Great storm.",

  // Nephilim order
  anak: "Biblical giant meaning 'necklace'.",
  goliath: "Giant warrior whose name means 'exile'.",
  og: "Rephaite giant king.",
  nimrod: "Biblical mighty hunter.",
  samyaza: "Leader of the Watchers meaning 'infamous seer'.",
  gadreel: "Watcher whose name implies 'wall of God'.",
  naarah: "Hebrew for 'maiden'.",
  zillah: "Hebrew for 'shade'.",
  adah: "Hebrew for 'ornament'.",
  nephira: "Oripheon form evoking 'nefilim daughter'.",
  anakiel: "'Anak of God', linking giant lineage to the divine.",
  seraphel: "Fused seraph/El meaning 'fiery one of God'.",
  enoch: "Hebrew for 'dedicated'.",
  jared: "Hebrew for 'descend'.",
  mahalalel: "Hebrew for 'praise of God'.",
  kenan: "Hebrew for 'possession'.",
  seth: "Hebrew for 'appointed'.",
  hybrid: "Being of mixed bloodlines.",
  fallen: "One who has descended from the heavens.",
  towering: "Sky-touching stature.",
  giant: "Colossal being of myth.",

  // Archon order
  sabaoth: "Hebrew for 'hosts' or 'armies'.",
  "ialda baoth": "Gnostic demiurge name meaning 'child of chaos'.",
  saklas: "Syriac for 'fool', title for the demiurge.",
  authades: "Gnostic epithets meaning 'self-willed'.",
  yao: "Variant of Iao, ineffable tetragrammaton.",
  sophia: "Greek for 'wisdom'.",
  barbelo: "Gnostic aeon representing divine womb.",
  zoe: "Greek for 'life'.",
  pronoia: "Greek for 'forethought'.",
  pistis: "Greek for 'faith'.",
  achamoth: "Lower Sophia, meaning 'wisdom'.",
  abraxas: "Mystic name combining 365 powers.",
  nous: "Greek for 'intellect'.",
  logos: "Greek for 'divine word'.",
  pleroma: "Fullness of the divine realm.",
  bythos: "Gnostic 'depth'.",
  sige: "Personification of silence.",
  ruler: "Title for governing archon.",
  archon: "Greek for 'ruler'.",
  eon: "Anglicized aeon meaning 'timeless age'.",
  cosmic: "Relating to the ordered universe.",
  prime: "First principle or origin.",

  // Dragonkin order
  alduin: "Dragontongue for 'devourer of the world'.",
  fafnir: "Norse dragon whose name means 'the embracer'.",
  kaedros: "Oripheon draconic for 'ember strategist'.",
  vythor: "Draconic title meaning 'sky furnace'.",
  aurelian: "From Latin aureus, 'golden'.",
  tharos: "Dragon tongue for 'flame guard'.",
  tiamara: "Variant of Tiamat, 'sea dragon mother'.",
  saphira: "From sapphire, 'deep-blue flame'.",
  kaida: "Japanese meaning 'little dragon'.",
  lyraeth: "Song-drake epithet meaning 'star-string'.",
  nythria: "Draconic for 'dusky ember'.",
  emberlyn: "Forge-born name meaning 'ember lake'.",
  ashwyn: "Ashen wind drake epithet.",
  dracel: "Short for draco-el, 'dragon of the divine'.",
  emberis: "Fused 'ember' and 'axis', meaning 'fire axis'.",
  skael: "Runic for 'scarred scale'.",
  talyn: "Old Breton talon meaning 'forehead' but used for 'claw'.",
  pyre: "Funeral fire.",
  ember: "Glowing coal.",
  wyrm: "Old English for dragon.",
  cinder: "Ash remnant of flame.",
  aerie: "Eagle's high nest, apt for sky dragons.",

  // Construct order
  ferrus: "From ferrum, meaning iron.",
  axion: "Mathematical term for self-evident truth, used for precision golems.",
  talos: "Bronze guardian of Crete.",
  cobal: "From cobalt, metallic guardian.",
  gideon: "Hebrew for 'mighty warrior', repurposed for paladin constructs.",
  quirin: "From Quirinus, protector of the state.",
  seraphiel: "Angelic engineer of divine machinery.",
  auriga: "Latin for 'charioteer'.",
  kalyx: "From calyx, protective outer shell.",
  vespera: "Latin for evening star, symbol of liminal charge.",
  ilyra: "Ilium + lyre, 'harmonic circuit'.",
  ophiel: "Angel of science, name meaning 'light of God'.",
  cipher: "Encrypted code.",
  alloy: "Fused metals.",
  vector: "Direction and magnitude, perfect for pathing.",
  nexus: "Connection hub.",
  parallax: "Shift in perspective, used for adaptive optics.",
  circuit: "Closed loop of energy.",
  cog: "Gear tooth.",
  pulse: "Rhythmic surge of power.",
  glyph: "Inscribed symbol containing code.",
  halo: "Ring of sanctified light.",

  // Eldritch order
  azathor: "Allusion to Azathoth, the nuclear chaos.",
  nyraem: "Whispered void name meaning 'silent rift'.",
  ultharic: "From Ulthar, city of dreamlands, meaning 'one who watches cats'.",
  kezroth: "Elder tongue for 'rift devourer'.",
  vorun: "Outer void word for 'hollow star'.",
  eldaros: "Eldritch voyager meaning 'ancient wanderer'.",
  azelia: "Starlit bloom adapted to void, 'night blossom'.",
  ythria: "Dreamsea term for 'sung depth'.",
  noctessa: "From noctis, 'nightfall sorceress'.",
  isyra: "Voidwind for 'echoing tide'.",
  velith: "Elder consonants meaning 'veil of thought'.",
  zenara: "Starward syllables meaning 'dawn beyond darkness'.",
  xhaos: "Stylized 'chaos', the yawning gulf.",
  voidra: "Personification of the void.",
  serolith: "Stone of secrets, 'memory fossil'.",
  quorin: "Elder signifying 'spiral mind'.",
  mhyrr: "Dark resin offered to unknowable gods.",
  abyl: "Obelisk tongue for 'without bottom'.",
  null: "Mathematical zero, absence.",
  chasm: "Abyssal gulf.",
  echo: "Returning sound from deep spaces.",
  abyss: "Limitless depth.",
  rift: "Tear between realities.",
};
